### ISSUE TITLE
Render emails in Next JS client component throws at renderToStaticMarkup

### ISSUE THREAD

**Issue by RomainGueffier** [resend/react-email#1080]
### Describe the Bug

I have a bug since upgrating to Next JS `14.x` with `@react-email/render` on client side.
I already saw similar issues but none of them really address my use case scenario.

I have monorepo project with an @email package full of `react-email` components exported as react. I need to render them at runtime to pass dynamic props.
With `react-hook-form` `onSubmit` I send as POST body to my mailer api the **stringified html** of my emails templates rendered on the spot. I will share later usage example, but see simple reproducing repo.

Since next 14 I have this error:
```
Error: Internal Error: do not use legacy react-dom/server APIs. If you encountered this error, please open an issue on the Next.js repo.
    at Object.r [as renderToStaticMarkup]
```

Maybe it was not intended for `render` to be used in the client bundle, but until now it was working fine. Advice on my usage is welcome.

Note: I can't revert to next 13 as there is serious issues with ISR cache.

Thanks for your awesome work to make email templating world easier 👍🏼 

### Which package is affected (leave empty if unsure)

@react-email/render

### Link to the code that reproduces this issue

https://github.com/RomainGueffier/react-email-next-14

### To Reproduce

Install and run project
In home page, visit server page => will work
In home page, visit client page => click `show/hide template` see console error shows error, crash

### Expected Behavior

Be able to render emails as string in client side

### What's your node version? (if relevant)

20

**Comment by gabrielmfern** [comment]
> I think this might be the same issue that I'm having here #1054 . There's a PR for a fix, that should be released pretty soon. #1079

I think this isn't a duplicate of #1054. This is a client side-issue, #1054 was a server-side one.

**Comment by gabrielmfern** [comment]
From what I've gathered of this issue what's happening is that Next stubs the `renderToStaticMarkup` and `renderToString` `react-dom/server` functions to throw this error for them to avoid usage of these functions on their code but it causes this error for us as well. 
On the server we can use other functions to avoid this issue but on the client there is really no alternative unless we use something that is not React specific for rendering. Maybe we should consider opening an issue on the Next repo for this

**Comment by RomainGueffier** [comment]
> @RomainGueffier What happens if you use renderAsync for this instead?

Didn't think about it, it just works 😱. If so, it is a life saver alternative as this bug is show-stopper for us.

I did push in a secondary branch the same code with `renderAsync` usage : 
- code: https://github.com/RomainGueffier/react-email-next-14
- preview: https://romaingueffier.github.io/react-email-next-14/

I put 6 use cases including server and client with both render and renderAsync

**Comment by RomainGueffier** [comment]
> **Edit**: it does not work for both case in safari
> 
> ```
> [Error] TypeError: ReadableByteStreamController is not implemented — 833-c8e66b6a37b3d4b4.js:21:208229
> 	(fonction anonyme) (472-0a5a1881c82c5cac.js:1:3789)
> 	ig (833-c8e66b6a37b3d4b4.js:21:170551)
> 	iS (833-c8e66b6a37b3d4b4.js:21:171813)
> 	iW (833-c8e66b6a37b3d4b4.js:21:194735)
> 	(fonction anonyme) (833-c8e66b6a37b3d4b4.js:21:209461)
> 	Promise
> 	(fonction anonyme) (833-c8e66b6a37b3d4b4.js:21:204775)
> 	(fonction anonyme) (833-c8e66b6a37b3d4b4.js:29:82208)
> 	s (833-c8e66b6a37b3d4b4.js:29:81311)
> ```

Seems like using a polyfill can fix it in safari for now: https://github.com/MattiasBuelens/web-streams-polyfill

**Comment by gabrielmfern** [comment]
> Seems like using a polyfill can fix it in safari for now: https://github.com/MattiasBuelens/web-streams-polyfill

That's really helpful, we'll probably use something like that for the `renderAsync` to be supported better.

**Comment by johnnycfg** [comment]
> > **Edit**: it does not work for both case in safari
> > ```
> > [Error] TypeError: ReadableByteStreamController is not implemented — 833-c8e66b6a37b3d4b4.js:21:208229
> > 	(fonction anonyme) (472-0a5a1881c82c5cac.js:1:3789)
> > 	ig (833-c8e66b6a37b3d4b4.js:21:170551)
> > 	iS (833-c8e66b6a37b3d4b4.js:21:171813)
> > 	iW (833-c8e66b6a37b3d4b4.js:21:194735)
> > 	(fonction anonyme) (833-c8e66b6a37b3d4b4.js:21:209461)
> > 	Promise
> > 	(fonction anonyme) (833-c8e66b6a37b3d4b4.js:21:204775)
> > 	(fonction anonyme) (833-c8e66b6a37b3d4b4.js:29:82208)
> > 	s (833-c8e66b6a37b3d4b4.js:29:81311)
> > ```
> 
> Seems like using a polyfill can fix it in safari for now: https://github.com/MattiasBuelens/web-streams-polyfill

How did you use polyfill in your project to fix it?

**Comment by RomainGueffier** [comment]
> How did you use polyfill in your project to fix it?

I use next js layout.tsx file to import polyfill directly:
```tsx
import Script from 'next/script'

type RootLayoutProps = {
  children: React.ReactNode
}

export default function RootLayout({
  children
}: RootLayoutProps) {
  return (
    <html>
      <body>
        {/*...code...*/}
        {/* distant cdn */}
        <Script src="https://unpkg.com/web-streams-polyfill/dist/polyfill.js" />
        {/* OR local file */}
        <Script src="/js/polyfill.js" />
      </body>
    </html>
  )
}
```

**Comment by gabrielmfern** [comment]
This has been fixed ever since [`@react-email/render@1.0.0`](https://github.com/resend/react-email/releases/tag/%40react-email%2Frender%401.0.0).

**Comment by LavransBjerkestrand** [comment]
For reference ReadableByteStreamController [isn't supported in Safari](https://caniuse.com/mdn-api_readablebytestreamcontroller), so stilling getting `ReadableByteStreamController is not implemented` on version 1.0.2. This issue is tracked at  #1732

**Comment by nusu** [comment]
Still getting `ReadableByteStreamController is not implemented` on Safari!, renderAsync and polyfill doesn't fix.
