### ISSUE TITLE
Preview app failing when NodeJS's version is not >=20

### ISSUE THREAD

**Issue by AngeloMaiuri** [resend/react-email#1235]
### Describe the Bug

Ran the automatic install commands to set up some boilerplate using `pnpm create email`.

When running `pnpm dev`, I get presented with the following error:

```
Error: The "path" argument must be of type string. Received undefined
```

pointing to the following code:

https://github.com/resend/react-email/blob/7028a581bac498bec90dce91277e0ec1de8f3221/packages/react-email/src/actions/get-emails-directory-metadata.ts#L67-L71

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

https://github.com/resend/react-email

### To Reproduce

Run `pnpm create email`, install the packages, run `pnpm dev`. 

### Expected Behavior

No error.

### What's your node version? (if relevant)

18

**Comment by GeovannyGil** [comment]
I am having the same problem.
<img width="951" alt="Captura de pantalla 2024-01-23 a la(s) 5 00 19 p  m" src="https://github.com/resend/react-email/assets/65850956/4ec3c51f-3091-4bd7-9feb-62bd598b3519">

**Comment by gabrielmfern** [comment]
Really weird issue, are you all using Windows?

**Comment by tim3w4rp** [comment]
Just had the same issue. Updating to `nodejs 21.6.1` helped.

**Comment by gabrielmfern** [comment]
@tim3w4rp Were you using Windows?

**Comment by GeovannyGil** [comment]
> Really weird issue, are you all using Windows?

No, I'm using macOS

**Comment by gabrielmfern** [comment]
@GeovannyGil Would you mind making a quick reproduction of the issue?

**Comment by tim3w4rp** [comment]
> @tim3w4rp Were you using Windows?

macOS 14.2.1 (23C71)
nodejs 19.8.1
using npm to run it

reproduction was basically same as the original post

**Comment by ifielder** [comment]
Upgrading to node `21.6.1` was the fix for me

**Comment by connorwinston** [comment]
The issue is that `dirent.path` was introduced in Node v20.1.0. 

```
(property) Dirent.path: string
The base path that this fs.Dirent object refers to.

@since — v20.1.0
```

**Comment by gabrielmfern** [comment]
PR open for this #1257, thanks @connorwinston for pointing this out.

**Comment by gabrielmfern** [comment]
Fixed a new canary release `react-email@2.1.0-canary.1` lmk if it works out for you all.

**Comment by kthompson** [comment]
@gabrielmfern I added `react-email@2.1.0-canary.1` and I am still presented with this issue.

Same stack trace is presented. 
Node v18.16.1
OSX
