### ISSUE TITLE
mjs build uses require

### ISSUE THREAD

**Issue by kentcdodds** [resend/react-email#1486]
### Describe the Bug

The module at [`@react-email/render/dist/index.mjs`](https://unpkg.com/browse/@react-email/render@0.0.15/dist/index.mjs) attempts to use `require` which is not supported in a native ESM environment (it's an `mjs` file so it's native ESM).

As a result, when calling `renderAsync`, you get the following error:

```
Error: Dynamic require of "stream" is not supported
```

This is because `require` is not defined in a module using native ESM.

### Which package is affected (leave empty if unsure)

@react-email/render

### Link to the code that reproduces this issue

https://github.com/epicweb-dev/epic-stack/pull/749

### To Reproduce

Attempt to use renderAsync with the `mjs` build.

### Expected Behavior

It renders properly without error.

### What's your node version? (if relevant)

v20.13.0

**Comment by pjamrozowicz** [comment]
@gabrielmfern any estimates for the new release date? This error is currently blocking me 😢

**Comment by gabrielmfern** [comment]
Just released the fix for this under canary. It should be working under `@react-email/render@0.0.16-canary.0` and `@react-email/components@0.0.20-canary.0`.

**Comment by YannHulot** [comment]
I am still getting this error even though I updated the packages to the canary versions.
I can't really share a repo with the issue though since the code is proprietary.

**Comment by YannHulot** [comment]
Just to add to my previous message. The error happens when I try to render and email in an API route on nextjs.

Its a very simple route. I tried changing the runtime to edge and node and still get the same issue.

The code looks like this:

```
 const html = await renderAsync(LoginWithMagicLink({ loginUrl: url }), {
      pretty: true,
    })
```

Nextjs version: 14.2.4 with pages router
@react-email/render: 0.0.16-canary.0
@react-email/components: 0.0.20-canary.0

**Comment by HananoshikaYomaru** [comment]
@YannHulot  I am the same problem. Local works fine but deployment failed. Are you using Vercel as deployment platform? Just curious is it possible that the problem happens on Vercel?

**Comment by gabrielmfern** [comment]
@YannHulot Can't reproduce the error on my side here. Tried the same dependency versions as well.

**Comment by ludu12** [comment]
Slight gotcha in updating to `react-email/components: 0.0.20-canary.0`.. For those using the `resend` [package](https://github.com/resend/resend-node/tree/canary) to render their component and looking for a workaround now, I think the render package needs to be overridden in package.json:

```
  "overrides": {
    "resend": {
      "@react-email/render": "0.0.16-canary.0"
    }
  },
```

**Comment by gabrielmfern** [comment]
@ludu12 Weird that you had this issue because the 0.0.20-canary.0 already includes that version of render.

[![image](https://github.com/resend/react-email/assets/88866334/728e4cac-4522-4bd0-ab68-16605a31d010)](https://www.npmjs.com/package/@react-email/components/v/0.0.20-canary.0?activeTab=code)

**Comment by PhilippLiebhart** [comment]
@ludu12 Thanks for the fix. Working now.

**Comment by GorvGoyl** [comment]
I'm facing this issue when i deploy to vercel (pages route, next.js: 14.2.4). Waiting for a fix. For now i've downgraded.

**Comment by gabrielmfern** [comment]
@GorvGoyl Does the canary not work for you?

**Comment by z-index-dev** [comment]
@gabrielmfern I'm having the same issue and happy to share what I'm seeing (pages router, next: "14.2.4"). Following the example docs exactly as [here](https://resend.com/docs/send-with-nextjs) just to get up and running.

`email-template.tsx`
> > export const EmailTemplate: React.FC<Readonly<EmailTemplateProps>> = ({
>   firstName,
> }) => (
>   <div>
>     <h1>Welcome, {firstName}!</h1>
>   </div>
> );

`send.ts`
> import type { NextApiRequest, NextApiResponse } from "next";
> import { Resend } from "resend";
> import { EmailTemplate } from "src/components/email-template";
> 
> const resend = new Resend(process.env.RESEND_API_KEY);
> 
> export default async (req: NextApiRequest, res: NextApiResponse) => {
>   const { data, error } = await resend.emails.send({
>     from: "Acme <onboarding@resend.dev>",
>     to: ["delivered@resend.dev"],
>     subject: "Hello world",
>     react: EmailTemplate({ firstName: "John" }),
>   });
> 
>   if (error) {
>     return res.status(400).json(error);
>   }
> 
>   res.status(200).json(data);
> };

In `send.ts` I'm getting the following error: Argument of type '{ from: string; to: string[]; subject: string; react: ReactNode; }' is not assignable to parameter of type 'CreateEmailOptions'. Subbing in `text` or `html` for `react` gets it to work

**Comment by isMattCoding** [comment]
If anyone is using yarn and having issues (like me), this is the fix that worked for me:

```
"resolutions": {
    "resend/@react-email/render": "0.0.16-canary.0"
  },
```

**Comment by gabrielmfern** [comment]
This has now been released under [`@react-email/render@0.0.16`](https://github.com/resend/react-email/releases/tag/%40react-email%2Frender%400.0.16). If anyone experiences this issue, let me know with a proper reproduction that I can clone and I will reopen.

**Comment by isMattCoding** [comment]
> If anyone is using yarn and having issues (like me), this is the fix that worked for me:
> 
> ```
> "resolutions": {
>     "resend/@react-email/render": "0.0.16-canary.0"
>   },
> ```

Just tested on my side, it works with 

```
"resolutions": {
    "resend/@react-email/render": "0.0.16"
  },
```

Now just waiting for https://github.com/resend/resend-node/pull/395 to be merged and deployed and I expect to be able to remove the resolutions.
