### ISSUE TITLE
Cannot render email | TypeError: undefined is not an object (evaluating 'Object.hasOwn(Z,"renderToReadableStream")')

### ISSUE THREAD

**Issue by amjed-ali-k** [resend/react-email#1745]
### Describe the Bug

I am getting this error when sending email from bun@latest.

```
TypeError: undefined is not an object (evaluating 'Object.hasOwn(Z,"renderToReadableStream")')
at hasOwn (native:1:1)
at /node_modules/@react-email/render/dist/node/index.mjs:99:14
at G (/node_modules/@react-email/render/dist/node/index.mjs:21:24) 
at processTicksAndRejections (native:7:39) 
```

My code sample 
```typescript

import * as React from "react";
import { render } from "@react-email/render";
import { Resend } from "resend";
import MedTravelBooking, {
  MedTravelBookingSubject,
  MedtravelProps,
} from "./emails/medtravel-submission";


export async function sendMedtravelEmailToAdmin(
  email: string,
  data: MedtravelProps,
): Promise<any> {
  try {
    await resend.emails.send({
      from: FROM_EMAIL,
      to: email,
      subject: MedTravelBookingSubject,
      html: await render(<MedTravelBooking data={data} />, {
        pretty: true,
      }),
    });
  } catch (error) {
    console.error(error);
  }
  return true;
}
```

### Which package is affected (leave empty if unsure)

@react-email/render

### Link to the code that reproduces this issue

-

### To Reproduce

```typescript

import * as React from "react";
import { render } from "@react-email/render";
import { Resend } from "resend";
import MedTravelBooking, {
  MedTravelBookingSubject,
  MedtravelProps,
} from "./emails/medtravel-submission";


export async function sendMedtravelEmailToAdmin(
  email: string,
  data: MedtravelProps,
): Promise<any> {
  try {
    await resend.emails.send({
      from: FROM_EMAIL,
      to: email,
      subject: MedTravelBookingSubject,
      html: await render(<MedTravelBooking data={data} />, {
        pretty: true,
      }),
    });
  } catch (error) {
    console.error(error);
  }
  return true;
}
```

### Expected Behavior

--

**Comment by doepnern** [comment]
Have been having the same problem in Bun. Downgrading to `0.0.20` fixed the problem for me. Seems to have been introduced at some point after that.

**Comment by gabrielmfern** [comment]
Tried it myself on a blank project that just plain console logs a simple email rendered and got no error. Can you share a minimal repo that reproduces the error? @amjed-ali-k

**Comment by doepnern** [comment]
I couldn't reproduce it locally either, happened in the oven/bun:2.0.0 docker image for me

**Comment by 1finedev** [comment]
+1 on this, getting same error on bun, ubuntu vps

<img width="833" alt="Screenshot 2024-10-26 at 05 33 45" src="https://github.com/user-attachments/assets/62c7f63a-6d8c-4fd6-b602-7533b2ad0d7b">

**Comment by 1finedev** [comment]
after a bit of research `bun add react@canary react-dom@canary` seems to fix my issue 

[Bun Guide](https://bun.sh/guides/ecosystem/ssr-react)

**Comment by amjed-ali-k** [comment]
### Reproduction of this issue.

@gabrielmfern  You can find the reprod [here](https://github.com/amjed-ali-k/react-email-bun-bundler-bug). 
Run bundled version using `bun run start` and it will throw the error.
https://github.com/amjed-ali-k/react-email-bun-bundler-bug

here is the screenshot
![image](https://github.com/user-attachments/assets/404a18d1-1720-46c7-86dd-d93078af2530)

**Comment by gabrielmfern** [comment]
Should be fixed on the latest canaries!

**Comment by thisislvca** [comment]
> bun add react@canary react-dom@canary

@gabrielmfern this fixed it for me. Tried all canaries from you guys and didn't fix the issue :)

**Comment by gabrielmfern** [comment]
@thisislvca your problem must be something else then, since it did work just fine in the original problem for this issue

here's the repro that it worked for https://github.com/amjed-ali-k/react-email-bun-bundler-bug

**Comment by jony89** [comment]
With latest canary: 
```
    "@react-email/components": "^0.0.37-canary.4",
    "react-email": "^4.1.0-canary.3",
```

I get : 

```
    error message: Object.hasOwn is not a function,
    error stack: TypeError: Object.hasOwn is not a function
    at /@react-email/components/node_modules/@react-email/render/dist/node/index.js:192:14
    at Generator.next (<anonymous>)
    at fulfilled (/@react-email/components/node_modules/@react-email/render/dist/node/index.js:50:24),

```
