### ISSUE TITLE
`render` does not work in the browser

### ISSUE THREAD

**Issue by hampustagerud** [resend/react-email#1953]
### Describe the Bug

Opening an issue since it was suggested to do that first instead of just opening a pull request 😄 

I am trying to render an email in the browser but the react server is not imported properly (see reproduction) 🙂 I have solved this locally by patching the package and changing [this line](https://github.com/resend/react-email/blob/canary/packages/render/src/browser/render.tsx#L56) like this:

```diff
- const reactDOMServer = await import('react-dom/server');
+ const reactDOMServer = (await import('react-dom/server')).default;
```

This issue is that importing modules dynamically in the browser returns a `Module` and not the default export which typescript seem to suggest. Not sure if typescript can be reconfigured to reflect this, or if there's a better solution than this. The tests seem to pass and I can use the render function when trying out the fix locally at least!

### Which package is affected (leave empty if unsure)

@react-email/render

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vitejs-vite-8gysj2qp?file=src%2Fmain.tsx

### To Reproduce

Use the `render` function in a browser.

### Expected Behavior

The email is rendered to HTML.

**Comment by wottpal** [comment]
+1

Facing the same issue when using react-email in a trigger.dev task node environment.

**Comment by philinit** [comment]
The bug appears in version 1.0.3 and later.
Version 1.0.2 works correctly.

**Comment by wottpal** [comment]
I can confirm, it's working on `1.0.2` w/o any issues.

**Comment by gabrielmfern** [comment]
seems like it only happens when running dev as well - when running with `vite preview` after build, it works

**Comment by wottpal** [comment]
> +1
> 
> Facing the same issue when using react-email in a trigger.dev task node environment. The patch fixes it.

@gabrielmfern As mentioned above, it's not only happening in dev mode for me but when using react-email in **production** environment via Trigger.dev. So it would be great if this could be escalated somehow. Still pinned to `1.0.2`.

**Comment by tobimori** [comment]
Can confirm that this happens w/ Vite + CF Vite Plugin, fixed by downgrading render to `1.0.2`.

**Comment by ijxy** [comment]
I ran into a similar/related when rendering dynamic previews in my applications.

Specifically, rendering was _silently_ failing on mobile devices (specifically iPhone/iPad) **only**.

Fortunately, using `renderToString` from `react-dom/server` directly "just works" to render the HTML.  I still use the exported render method on the server.

Here's my Preview component, in case anyone finds it useful:

```jsx
"use client";

import { JSX, useEffect, useState } from "react";
import { renderToString } from "react-dom/server";

import { InlineFrame } from "@internal/react"; // this is just a wrapper around `<iframe />`

export type EmailPreviewProps = {
  template: JSX.Element;
};

export function EmailPreview({ template }: EmailPreviewProps) {
  const [html, setHtml] = useState<string | null>(null);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    Promise.resolve(renderToString(template))
      .then((rendered) => {
        setHtml(rendered);
        setError(null);
      })
      .catch((e) => {
        setHtml(null);
        setError(new Error(e));
      });
  }, [template]);

  return (
    <>
      {!!html ? (
        <InlineFrame responsive srcDoc={html} />
      ) : !!error ? (
        <p>Something went wrong...</p>
      ) : (
        <p>Loading...</p>
      )}
    </>
  );
}
```

**Comment by gabrielmfern** [comment]
Should be fixed in [@react-email/render@1.1.2](https://github.com/resend/react-email/releases/tag/%40react-email%2Frender%401.1.2)/[@react-email/render@1.1.2](https://github.com/resend/react-email/releases/tag/%40react-email%2Frender%401.1.2)

**Comment by wottpal** [comment]
Nope, unfortunately still not working in Trigger.dev node environment. – Shall I open a new issue?

… Pinning to `v1.0.2` again!

```
[trigger] ○ May 14, 17:47:25.417 ->  20250514.8 | emails/magic-link | run_t7qhonmf2ymm5f5hk49ps.1
[trigger] ○ May 14, 17:47:26.228 ->  20250514.8 | emails/magic-link | run_t7qhonmf2ymm5f5hk49ps.1 | Error (retrying skipped) (773.4ms)
[trigger] 
[trigger] TypeError: reactDOMServer.renderToPipeableStream is not a function
[trigger] at __spreadValues.selectors (file:///[…]/node_modules/resend/node_modules/@react-email/render/dist/node/index.mjs:162:37)
[trigger] at new Promise (<anonymous>)
[trigger] at file:///[…]/node_modules/resend/node_modules/@react-email/render/dist/node/index.mjs:161:11
[trigger] at Generator.next (<anonymous>)
[trigger] at fulfilled (file:///[…]/node_modules/resend/node_modules/@react-email/render/dist/node/index.mjs:24:24)
[trigger] 
```

**Comment by gabrielmfern** [comment]
@wottpal yeah would be nice if you could, seems to be a problem that's related but not the same as the original issue

I think it might definitely be something with ESM/CJS compatibility here

**Comment by eivindml** [comment]
In Safari I also get error with the `render()` method on the latest version of react email, in the Browser. Using the `renderString()` from `react-domain/server` works.

**Comment by JWPapi** [comment]
@wottpal 

> reactDOMServer.renderToPipeableStream is not a function

this happens when react-email is trying to use  react-dom 18.x, where the function would be located in the `default` prop. force a `19.1.1` installation and it should work (it did for me)
