### ISSUE TITLE
Preview Server had an error: TypeError: Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by anaclumos** [resend/react-email#2276]
### Describe the Bug

```
bun email:dev                                                                            
$ email dev --port 5678
    React Email 4.0.15
    Running preview at:          http://localhost:5678

  ✖  Preview Server had an error: TypeError: Cannot read properties of undefined (reading 'filter')

    shutting down dev server
error: script "email:dev" exited with code 1
```

### Link to the code that reproduces this issue

https://github.com/everynews/everynews

### To Reproduce

Run `bun email:dev`

### Expected Behavior

`bun email:dev` should run

### What's your node version? (if relevant)

v22.15.0

**Comment by anaclumos** [comment]
I temporarily downgraded to React Email v3 to workaround this issue. Bumping RE to v4 still gives the same error.

**Comment by gabrielmfern** [comment]
The error seems to just not be present when installing with npm here

**Comment by renansigolo** [comment]
I'm having the same issue here using Node v22.17.0 and npm 10.9.2
I was able to get it up and running until v4.0.8
```
> email dev

    React Email 4.0.8
    Running preview at:          http://localhost:3000

  ✔ Ready in 0.3s
```

And it looks like this error was introduced in v.4.0.9 with the error message:
```
> email dev

    React Email 4.0.9
    Running preview at:          http://localhost:3000

  ⠙ Getting react-email preview server ready...
  ✖ Getting react-email preview server ready...


shutting down dev server
```

Then on v.4.0.12 the message changes to:
```
> email dev

    React Email 4.0.12
    Running preview at:          http://localhost:3000

  ✖  Preview Server had an error: TypeError: Cannot read properties of undefined (reading 'filter')

    shutting down dev server
```

**Comment by wottpal** [comment]
same here with bun! 🙋‍♂️

**Comment by WoetDev** [comment]
Also having this error with:
- node v22.16.0 running on WSL2
- pnpm
- react-email and @react-email/preview-server v4.1.3

Can confirm it's also working when I downgrade react-email to v4.0.8, which is the earliest working version for me.

**Comment by jonasbuechel** [comment]
Same here it works with v4.0.8, but stops working v4.0.9
Node v22.17.0 
npm 10.9.2

I reduced templates in /email to the one from [the gudie](https://react.email/docs/getting-started/manual-setup), and deleted all others (also .DS_Store).

**Comment by arauser** [comment]
+1

**Comment by martingrondein** [comment]
+1

**Comment by aaroncraigongithub** [comment]
Having the same issue and I can't downgrade to 4.0.8:

```
No matching version found for @react-email/preview-server@4.0.8 while fetching it from https://registry.npmjs.org/
```

Any word from maintainers as to when this might get resolved. We're evaluating Resend for a new project so this is a bit of a showstopper for us.

**Comment by ShooTeX** [comment]
> Having the same issue and I can't downgrade to 4.0.8:
> 
> ```
> No matching version found for @react-email/preview-server@4.0.8 while fetching it from https://registry.npmjs.org/
> ```
> 
> Any word from maintainers as to when this might get resolved. We're evaluating Resend for a new project so this is a bit of a showstopper for us.

try downgrading react-email, not the preview server

**Comment by gabrielmfern** [comment]
Investigating this right now, it seems to be happening even outside of bun now. I think it might be some sort of incompatibility with a newer Next.js versions that ends up borking the preview server because it uses an older version on the build.

**Comment by gabrielmfern** [comment]
Found a workaround for now, it should work if you add an override for `next`:

```json
    "overrides": {
      "next": "15.3.2"
    }
```

**Comment by StephenHaney** [comment]
Using Bun, trying out React Emails and also getting this error. I tried the `next` override but I'm still getting the same error.

This is in a Bun monorepo.

```
{
  "name": "@paper/emails",
  "version": "0.0.1",
  "type": "module",
  "scripts": {
    "dev": "email dev"
  },
  "dependencies": {
    "@react-email/components": "0.3.1",
    "react-dom": "^19.0.0",
    "react": "^19.0.0"
  },
  "devDependencies": {
    "@react-email/preview-server": "4.2.0",
    "@types/react": "^19.0.1",
    "@types/react-dom": "^19.0.1",
    "react-email": "4.2.0"
  },
  "overrides": {
    "next": "15.3.2"
  }
}

```

```
❯ bun run dev
$ email dev
    React Email 4.2.0
    Running preview at:          http://localhost:3000

  ✖  Preview Server had an error: TypeError: Cannot read properties of undefined (reading 'filter')
```

**Comment by aaroncraigongithub** [comment]
Confirming this worked for me with @react-email 4.2.0.

For overrides, I had to nest it inside "pnpm" in my root package.json, so:

```
"pnpm": {
  "overrides": {
    "next": "15.3.2"
  }
}
```

**Comment by limegorilla** [comment]
> For overrides, I had to nest it inside "pnpm" in my root package.json, so:

For users with your react-email implementation inside a monorepo package I found I needed to override it in my root package.json and ensure that the specific version was keyed inside my email package:

```json
// package.json (root)
{
...
"pnpm": {
    "overrides": {
      "@acme/email>next": "15.3.2" // where @acme/email is the name of your package
    }
  }
}
```

```json
// ./packages/email/package.json
{
"name": "@acme/email", // <-- Same as above!
...
"devDependencies": {
    "next": "15.3.2",
  }
}

**Comment by gabrielmfern** [comment]
@StephenHaney worked when trying it out with Bun myself. Maybe in your case, bun didn't re-resolve the dependencies? I've had a few situations where bun is kinda finicky with that, so it might be worth deleting your `node_modules`/your `bun.lock`

**Comment by gabrielmfern** [comment]
Should be fixed in the latest [`react-email@4.2.1`](https://github.com/resend/react-email/releases/tag/react-email%404.2.1)/[`@react-email/preview-server@4.2.1`](https://github.com/resend/react-email/releases/tag/%40react-email%2Fpreview-server%404.2.1).

**Comment by xmlking** [comment]
upgraded to react-email@4.2.1 / @react-email/preview-server@4.2.1.
still getting error
<img width="1299" height="566" alt="Image" src="https://github.com/user-attachments/assets/9c3535d6-1e16-42ed-86c9-740c41fa2e0e" />

**Comment by gabrielmfern** [comment]
@xmlking seems to be a different problem, perhaps introduced in `@react-email/preview-server@4.2.0`. Could you make another issue for that with a proper minimal reproduction? Mention your package manager and Node.js version as well, thanks!

**Comment by xmlking** [comment]
I fixed it, the problem was my packages/email/package.json had 
Type: module 
That was causing above problem.
After I removed , it worked 

> [@xmlking](https://github.com/xmlking) seems to be a different problem, perhaps introduced in `@react-email/preview-server@4.2.0`. Could you make another issue for that with a proper minimal reproduction? Mention your package manager and Node.js version as well, thanks!

**Comment by gabrielmfern** [comment]
@xmlking that shouldn't be a problem, can you still make an issue for it?

**Comment by xmlking** [comment]
> [@xmlking](https://github.com/xmlking) that shouldn't be a problem, can you still make an issue for it?

created https://github.com/resend/react-email/issues/2379
