### ISSUE TITLE
Objects are not valid as a React child

### ISSUE THREAD

**Issue by modejota** [resend/react-email#2429]
### Describe the Bug

Trying to render a React component generates the the following error:
```zig
Error: Objects are not valid as a React child (found: object with keys {tag, props, key, children, isEscaped, localContexts}). If you meant to render a collection of children, use an array instead. at retryNode (C:\Users\produ\Desktop\trackyrs\node_modules\react-dom\cjs\react-dom-server.bun.development.js:7192:13) at renderNodeDestructive (C:\Users\produ\Desktop\trackyrs\node_modules\react-dom\cjs\react-dom-server.bun.development.js:7065:7) at renderNode (C:\Users\produ\Desktop\trackyrs\node_modules\react-dom\cjs\react-dom-server.bun.development.js:7505:14) at renderElement (C:\Users\produ\Desktop\trackyrs\node_modules\react-dom\cjs\react-dom-server.bun.development.js:6690:18) at retryNode (C:\Users\produ\Desktop\trackyrs\node modules\react-dom\cjs\react-dom-server.bun.development.js:7126:17) at performWork (C:\Users\produ\Desktop\trackyrs\node_modules\react-dom\cjs\react-dom-server.bun.development.js:7927:13) at performMicrotask (unknown) at processTicksAndRejections (native:7:39)" data-cstck=" at Suspense (&lt;anonymous&gt;)"></template><!--/$--> 
```

The returned HTML logged in the console is as follows:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtm11/DTD/xhtm11-transitional.dtd"><!--$!--><template data-msg="Switched to client rendering bec ause the server rendering errored:
```

Email is sent, but the body is empty.

Context: being used as part of better-auth workflow, called from the Next.js app, server being a Hono.js one

### Which package is affected (leave empty if unsure)

@react-email/components

### Link to the code that reproduces this issue

Private repository for the time being

### To Reproduce

package.json used:
```json
{
	"name": "@trackyrs/email",
	"version": "0.0.0",
	"type": "module",
	"exports": {
		"./email-service": "./sender/email-service.ts",
		"./templates/*": "./emails/*"
	},
	"sideEffects": false,
	"devDependencies": {
		"@react-email/preview-server": "4.2.8",
		"@trackyrs/typescript-config": "workspace:*",
		"@types/nodemailer": "^7.0.1"
	},
	"dependencies": {
		"@react-email/components": "0.5.1",
		"dotenv": "^17.2.1",
		"nodemailer": "^7.0.5",
		"react": "19.1.1",
		"react-dom": "19.1.1",
		"react-email": "4.0.17"
	}
}
```
tsconfig.json used:
```json
{
	"extends": "@trackyrs/typescript-config/base.json",
	"compilerOptions": {
		"module": "esnext",
		"moduleResolution": "bundler",
        "lib": ["ESNext", "DOM", "DOM.Iterable"],
        "target": "esnext",
        "resolveJsonModule": true,
		"isolatedModules": true,
		"jsx": "react-jsx",
		"incremental": true,
		"outDir": "./dist",
		"rootDir": "./",
		"baseUrl": "./"
	},
	"include": ["./**/*"],
	"exclude": ["node_modules", "dist"]
}
```

Code to send the email is as follows:
```typescript
	static async sendPasswordResetEmail({
		user,
		url,
		token,
	}: ResetPasswordProps) {
		try {
			const resetLink = `${url}?token=${token}`;
            const emailHtml = await render(
                MyEmail()
            );
            
			const mailOptions = {
				from: process.env.EMAIL_USER,
				to: user.email,
				subject: "Trackyrs - Password reset",
				html: emailHtml,
			};

			await EmailService.getTransporter().sendMail(mailOptions);
		} catch (error) {
			throw error;
		}
	}
```

MyEmail is just a copy-paste from the docs:
```typescript
import { Button, Html } from "@react-email/components";
import * as React from "react";

export const MyEmail = () => {
	return (
		<Html>
			<Button
				href="https://example.com"
				style={{ background: "#000", color: "#fff", padding: "12px 20px" }}
			>
				Click me
			</Button>
		</Html>
	);
};

export default MyEmail;
```

- Prior versions of react-email, @react-email/components, react have also been tested; issue remain. 
- Tsconfig jsx mode also tried as react-jsx, react and preserve; issue remains

### Expected Behavior

Email sent with propered rendered body

### What's your node version? (if relevant)

Bun 1.2.21 | Windows

**Comment by mnlfischer** [comment]
Same here but only in Playwright e2e tests. I am using React Router Framework mode.

``` typescript
export const sendEmail = async ({
  react,
  ...options
}: {
  to: string;
  subject: string;
} & (
  | { html: string; text: string; react?: never }
  | { react: ReactElement; html?: never; text?: never }
)) => {
  const from = "...";

  const email = {
    from,
    ...options,
    ...(react ? await renderReactEmail(react) : null),
  };
  ...
};

async function renderReactEmail(react: ReactElement) {
  const [html, text] = await Promise.all([
    render(react),
    render(react, { plainText: true }),
  ]);
  return { html, text };
}

```

```tsx
export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: "sqlite",
  }),
  telemetry: {
    enabled: false,
  },
  plugins: [
    magicLink({
      sendMagicLink: async ({ email, url }) => {
        const { status, error } = await sendEmail({
          to: email,
          subject: "Your login link...",
          react: <LoginEmail magicLink={url} />,
        });

        if (status === "error") {
          throw new Error(error.message);
        }
      },
    }),
  ],
});
```

```tsx
export function LoginEmail({ magicLink }: { magicLink: string }) {
  return (
    <E.Html lang="en" dir="ltr">
      <E.Container>
        <p>
          <E.Text>Click on the link to login to your account:</E.Text>
        </p>
        <E.Link href={magicLink}>{magicLink}</E.Link>
      </E.Container>
    </E.Html>
  );
}
```

**Comment by fstodulski** [comment]
I have same issue.

```
5099 |           task,
5100 |           node._currentValue,
5101 |           childIndex
5102 |         );
5103 |       childIndex = Object.prototype.toString.call(node);
5104 |       throw Error(
                   ^
error: Objects are not valid as a React child (found: object with keys {tag, props, key, children, isEscaped, localContexts}). If you meant to render a collection of children, use an array instead.
      at retryNode (/Users/franciszekstodulski/Dev/@others/wizytka/node_modules/react-dom/cjs/react-dom-server.bun.production.js:5104:13)
      at renderNodeDestructive (/Users/franciszekstodulski/Dev/@others/wizytka/node_modules/react-dom/cjs/react-dom-server.bun.production.js:4857:7)
      at renderNode (/Users/franciszekstodulski/Dev/@others/wizytka/node_modules/react-dom/cjs/react-dom-server.bun.production.js:5424:14)
      at renderElement (/Users/franciszekstodulski/Dev/@others/wizytka/node_modules/react-dom/cjs/react-dom-server.bun.production.js:4665:18)
      at retryNode (/Users/franciszekstodulski/Dev/@others/wizytka/node_modules/react-dom/cjs/react-dom-server.bun.production.js:5063:16)
      at performWork (/Users/franciszekstodulski/Dev/@others/wizytka/node_modules/react-dom/cjs/react-dom-server.bun.production.js:5904:13)

html <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><!--$!--><template></template><!--/$-->
```

Email is sending, but it's empty. 
Tried to downgrade packages. 
Created fresh one project. 


I have a Hono running on Bun.

**Comment by fstodulski** [comment]
@mnlfischer any luck with it? Did u manage to fix it on your side?

**Comment by mnlfischer** [comment]
@fstodulski my issue was that I try to use server side functions inside the frontend part of my e2e tests.

**Comment by fstodulski** [comment]
Fixed it - Check if the project that imports email templates and sends them - have correct tsconfig and deps installed. 
In my case, my Hono app - Backend - that imports templates from react-email package and renders them had incorrect tsconfig for jsx and missing few deps.

**Comment by CodingDive** [comment]
I'm running into the same issue, but only when starting the preview server `"@react-email/preview-server": "4.3.2"`. The emails still get sent correctly (with a body), but I can't preview them. I tried to pin a newer version of react, as I thought it was a react version mismatch but it didn't help.

```
  "pnpm": {
    "overrides": {
      "react": "^19.2.0",
      "react-dom": "^19.2.0"
    }
  }
```

Here is the full error when i click on any of the emails in the preview. Despite pinning react 19.2, it still errors out with 18.3.1.

```
Error: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
 at renderNodeDestructiveImpl (node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6256:10)
 at renderNodeDestructive (node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:13)
 at renderNode2 (node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6336:11)
 at renderSuspenseBoundary (node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:5657:4)
 at renderElement (node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6071:10)
 at renderNodeDestructiveImpl (node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:10)
 at renderNodeDestructive (node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:13)
 at retryTask (node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6605:4)
 at performWork (node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6653:6)
 at Immediate.<anonymous> (node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6980:11)
```

**Comment by patr0cl0** [comment]
addind `/** @jsxImportSource react */` at the start of all of my templates/emails did the fix for me on this issue, im using hono on a monorepo btw.

I believe this is due hono having its own jsx support which conflicts with react compilation (being a dependecy of @react-email/components) or something like that, hope this helps someone

**Comment by lucashfreitas** [comment]
same here, I am using hono JS in the backend and adding /** @jsxImportSource react */ at the start did the magic.

**Comment by gabrielmfern** [comment]
I'm sorry this isn't enough to reproduce easily, but this kind of error is generally a mismatch between React and React DOM versions. If anyone shares a minimal reproduction for this, I'll reopen.

**Comment by lucashfreitas** [comment]
@gabrielmfern  most examples of Resend are built around Next.js, which handles React server rendering very well out of the box. However, there are many other backend frameworks in the Bun/Node ecosystem  like honojs, elysia, and others, which people may also want to use with Resend.

For example, HonoJS has its own approach to rendering JSX on the server. While Resend is a top-class framework with excellent DX, I couldn’t find any guides or examples showing how to use Resend + @react-email in backend-only frameworks like Hono or Elysia, instead of full-stack frameworks like Next.js.

In the case of HonoJS, using @react-email’s render can lead to issues like the ones @patr0cl0 mentioned. As a result, anyone trying to use Resend / React Email with Hono may run into the same problems. The current docs  https://react.email/docs/integrations/resend don’t really apply and work when you’re using a backend framework like Hono.

I’m not sure how many use cases there are for using Resend with backends other than Next.js, or whether this is a primary target market for Resend / React Email. But this did cost us some time debugging before we understood why it wasn’t working.

Maybe a simple guide or documentation section explaining how to use resend + react-email with different backend frameworks (not only Next.js) could be helpful? Or a simple document on react/email stating that it uses React Server under the hood and frameworks that replace or override server rendering on react might need an extra tick?

On the other hand, I understand this might be an edge case and a relatively rare issue, possibly even specific to HonoJS. If that’s the case, it totally makes sense for this not to be a priority right now.

Maybe in the future, if more people run into this and come back to the same issue, that could be a good signal to revisit it 🙂

Thank you very much.
